//
//  Created by VT on 16.11.25.
//  Copyright © 2025 Volker Thieme. All rights reserved.
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//  
/// Maximum likelihood fitter for the Poisson distribution in SwiftyStats.

import SwiftyStatsPrelude
extension MLEFitter {
    /// Fits a Poisson(λ) distribution by maximum likelihood.
    ///
    /// Parameterization and support
    /// - Intensity `λ > 0`.
    /// - Support for observations: `x ∈ {0, 1, 2, …}`.
    ///
    /// Probability mass function
    /// - P(X = x | λ) = e^{−λ} λ^x / x!, for x = 0,1,2,… .
    ///
    /// Log-likelihood
    /// - For observations `x₁,…,x_n`, the log-likelihood is
    ///   ℓ(λ) = Σ [ x_i · log λ − λ − log(x_i!) ].
    /// - The analytic MLE is `λ̂ = (1/n) Σ x_i` (the sample mean). The numerical optimizer should
    ///   recover this under regular conditions.
    ///
    /// Implementation details
    /// - The positivity constraint `λ > 0` is enforced via the solver’s positive transform
    ///   generated by `makeParamSpecs(for: .poisson, data:)`.
    /// - Per-observation log-pmf and analytic score are delegated to
    ///   `SwiftyBoost.Distribution.Poisson(lambda:)`.
    /// - This wrapper enables covariance (θ-space) and diagnostics by default.
    ///
    /// - Parameters:
    ///   - data: Non-empty sample of counts. Mathematically, each element should be an integer `x ≥ 0`.
    ///           Invalid inputs are rejected by the underlying distribution and penalized in the objective.
    ///   - optimizer: Local optimizer to use (`.nelderMead`, `.bfgs`, or `.lbfgs`). Default is `.lbfgs`.
    ///   - options: Optional solver options. If `nil`, sensible defaults are used and adjusted to compute covariance and enable diagnostics.
    ///
    /// - Returns: An `MLEResult<T>` with:
    ///   - `thetaHat = [λ̂]`,
    ///   - `logLik` (maximized log-likelihood),
    ///   - convergence flags and evaluation counts,
    ///   - optional covariance and diagnostics when enabled.
    ///
    /// - Precondition: `data` must be non-empty.
    public static func fitPoisson(
        _ data: [T],
        optimizer: OptimizerKind = .lbfgs,
        options: MLEOptimizationOpts<T>? = nil
    ) -> MLEResult<T> {
        precondition(!data.isEmpty)
        let dummy = MLEProblem<T>(data: data, logpdf: { _, _ in 0 }, paramSpecs: [.init(.real, initial: 0)])
        let specs = dummy.makeParamSpecs(for: .poisson, data: data)

        let logPDF: @Sendable (T, [T]) -> T = { x, theta in
            do {
                let lambda = theta[0]
                if !(lambda > .zero) { return T.infinity }
                let dist = try SwiftyBoost.Distribution.Poisson<T>(lambda: lambda)
                let res = try dist.logPdf(x)
                return res
            }
            catch _ {
                return T.infinity
            }
        }

        let gradLogPdf: @Sendable (T, [T]) -> [T] = { x, theta in
            do {
                let lambda = theta[0]
                if !(lambda > T.zero) { return [T.nan] }
                let dist = try SwiftyBoost.Distribution.Poisson<T>(lambda: lambda)
                let res = dist.score(x: x, lambda: lambda)
                return [res]
            }
            catch _ {
                return [T.nan, .nan]
            }
        }
        let problem = MLEProblem<T>(data: data, logpdf: logPDF, gradlogpdf: gradLogPdf, paramSpecs: specs)
        var opts = options ?? MLEOptimizationOpts<T>()
        opts.computeCovariance = true
        opts.optimizer = optimizer
        opts.diagnosticsEnabled = true
        return MLESolver.fit(problem, options: opts)
    }
}
